all: build

build:
	javac Minlexbfs.java
	javac Revedges.java
	javac Rtd.java
	c++ -o disjcnt disjcnt.cpp
	

run-p1:
	java Minlexbfs

run-p2:
	./disjcnt

run-p3:
	java Rtd

run-p4:
	java Revedges
clean: 
	rm *.class
